---
  environment: production
  chdir: /home/chat/
  address: 204.232.194.90
  user: root
  group: root
  port: 8080
  pid: /home/chat/tmp/thin.pid
  rackup: /home/chat/config.ru
  log: /home/chat/log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true